### ISSUE TITLE
Incompabitble protoc version

### ISSUE THREAD

**Issue by tmoeller4** [arubior/bass-superpixels#1]
Hi,
when compiling bass-superpixels, I'm getting the following error:

```
[ 18%] Building CXX object CMakeFiles/FastRCNN.dir/src/FastRCNN.cpp.o
In file included from /vol/workspace/bass-superpixels/code/./include/caffe/blob.hpp:9:0,
                 from /vol/workspace/bass-superpixels/code/./include/caffe/caffe.hpp:7,
                 from /vol/workspace/bass-superpixels/code/./include/CaffeCls.hpp:4,
                 from /vol/workspace/bass-superpixels/code/src/FastRCNN.cpp:1:
/vol/workspace/bass-superpixels/code/./include/caffe/proto/caffe.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^
/vol/workspace/bass-superpixels/code/./include/caffe/proto/caffe.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^
/vol/workspace/bass-superpixels/code/./include/caffe/proto/caffe.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^
In file included from /vol/workspace/bass-superpixels/code/./include/caffe/caffe.hpp:16:0,
                 from /vol/workspace/bass-superpixels/code/./include/CaffeCls.hpp:4,
                 from /vol/workspace/bass-superpixels/code/src/FastRCNN.cpp:1:
/vol/workspace/bass-superpixels/code/./include/caffe/util/io.hpp:8:18: fatal error: hdf5.h: No such file or directory
compilation terminated.

```
My Protoc Version is 2.6.1. How can I recompile caffe.pb.h with my protoc version?
Any help is greatly appreciated :-)

**Comment by arubior** [comment]
Hi @tmoeller4 , I've just downloaded, compiled and executed the code with protoc 2.5.0 and it worked. 

You can [install that version](https://jugnu-life.blogspot.com/2013/09/install-protobuf-25-on-ubuntu.html) and use it for the compilation (make sure you're using the right one with `which protoc`).

Regarding the last error (`fatal error: hdf5.h: No such file or directory`), taking a look at [this issue](https://github.com/NVIDIA/DIGITS/issues/156) might help you.

Please, let me know if you make it work.

**Comment by tmoeller4** [comment]
Thank you @arubior , it works with the protoc version you recommended. Some issues occurred during building and could be solved. Just for reference for other users, I list them here:

- Missing Dependencies: libopencvblas-dev (sudo apt-get install libopenblas-dev) and all the dependencies here: https://github.com/BVLC/caffe/wiki/Commonly-encountered-build-issues
- If the hdf5 libraries are not found, add the directory to the CMakeLists.txt (e.g LINK_DIRECTORIES(/usr/lib/x86_64-linux-gnu/hdf5/serial/))
- If the snappy library is not found create a symlink named libsnappy.so pointing to your version of libsnappy
- if the hdf5 header are not found pass the hdf5 directory during the cmake call (e.g: cmake -DCMAKE_CXX_FLAGS=-isystem\ /usr/include/hdf5/serial/ ..)  [I prefer this solution to the ones in the link you've sent]

Best regards and thanks again for your help
